### PR TITLE
Remove DNS cache

### PR DESCRIPTION
**Pull request by nurlan-issin**

### CODE REVIEW

**Comment by vadmeste** [comment]
@nurlan-issin can you provide more description why this PR is needed ?

**Comment by vadmeste** [comment]
@nurlan-issin It looks like there is DNS refresh mechanism in the code. Instead of removing the DNS cache code, can you just add a code to refresh ? it is already documented here, https://github.com/rs/dnscache#usage

**Comment by nurlan-issin** [comment]
I believe that caching should be handled by a caching DNS server.
The current implementation of dnscache ignores the ttl value of the dns record.

**Comment by harshavardhana** [comment]
> I believe that caching should be handled by a caching DNS server.
> The current implementation of dnscache ignores the ttl value of the dns record.

@nurlan-issin that is the design choice, you can fix your PR and update it here. Otherwise we will fix.

**Comment by nurlan-issin** [comment]
@harshavardhana I'm not developer, I'm sysadmin. Can you fix this byself?

**Pull request closed without merging**
