### PR TITLE
Add host override option

### PR DESCRIPTION
**Pull request by kvaps**
Added new `--host` option to override the host header for the requests:

```diff
 NAME:
   ./sidekick - High-Performance sidecar load-balancer
 
 USAGE:
   ./sidekick - [FLAGS] SITE1 [SITE2..]
 
 FLAGS:
   --address value, -a value          listening address for sidekick (default: ":8080")
   --health-path value, -p value      health check path
   --health-port value                health check port (default: 0)
   --health-duration value, -d value  health check duration in seconds (default: 5)
   --insecure, -i                     disable TLS certificate verification
   --log, -l                          enable logging
   --trace, -t                        enable request tracing
   --quiet, -q                        disable console messages
   --json                             output sidekick logs and trace in json format
   --debug                            output verbose trace
   --cacert value                     CA certificate to verify peer against
   --cert value                       client certificate file
   --key value                        private key file name
+  --host value                       override host for the requests
   --help, -h                         show help
   --version, -v                      print the version
```

This allows to send all the requests to the specific host, by overriding client request.

### CODE REVIEW

**Comment by kvaps** [comment]
Example usage:

* put kube-apiserver behind the nginx-ingress (eg. `kubernetes.example.org`)
* run local proxy:
  ```
  ./sidekick \
    --health-path=/healthz \
    --address 127.0.0.1:6443 \
    --cacert=/etc/kubernetes/pki/ca.crt \
    --host=kubernetes.example.org \
    https://kubernetes.example.org
  ```
* connet kubelet to `localhost:6443`

**Comment by kvaps** [comment]
PR rebased

**Comment by harshavardhana** [comment]
Isn't this a security problem @kvaps allowing this would invalidate any requests which HTTP header based authentication such as AWS S3.

You are allowing sort of signature replays in some manner here

**Comment by kvaps** [comment]
Hi, of course if headers are signed you can't do anything here.
I know this the main use case of sidekick is S3 proxy for minio, my use case is bit different.

I like the idea of sidekick that it is lightweight HTTP-proxy with health checks, but S3 is not only way how you can use it.

**Comment by harshavardhana** [comment]
> Hi, of course if headers are signed you can't do anything about it.
> I know that the main usage of sidekick is S3 proxy for minio, my use case is bit different.
> I just need lightweight HTTP-proxy for loadbalancing between few kube-apiservers.
> 
> I like the idea of sidekick for providing lightweight HTTP-proxy with the health checks, but S3 is not the only way how you can use it

This is fine just mention that using this with S3 API can cause signature issues, we should state that only use this option if you do not load balancing S3 traffic.

**Pull request closed without merging**
